baseURL: "https://blog.bbroster.com/"
languageCode: "en-us"
title: "BB Roster Blog"
theme: "paper-mod"

params:
  defaultTheme: auto
  homeInfoParams:
    Title: Welcome Coach,
    Content: Here you'll find the latest news on updates for https://bbroster.com
menu:
  main:
    - identifier: tags
      name: tags
      url: /tags/
      weight: 20
    - identifier: bbroster
      name: bbroster.com
      url: https://bbroster.com
      weight: 30

  # socialIcons: # optional
  #     - name: "<platform>"
  #         url: "<link>"
  #     - name: "<platform 2>"
  #         url: "<link2>"
