baseURL: "https://bbroster.com/"
languageCode: "en-us"
title: "BB Roster"
theme: "paper-mod"

params:
  homeInfoParams:
    Title: Welcome Coach,
    Content: Here you'll find the latest news and update notes for https://bbroster.com

  # socialIcons: # optional
  #     - name: "<platform>"
  #         url: "<link>"
  #     - name: "<platform 2>"
  #         url: "<link2>"
